---
title: "상관계수 in r"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	comment = "#",
	collapse = T
)
pg <- palmerpenguins::penguins
library(tidyverse)
```

## 상관계수 in r

```{r}
pg_adelie <- pg %>% 
  filter(species == "Adelie")
```

```{r}
cor(pg_adelie$bill_length_mm, pg_adelie$bill_depth_mm, use = "complete.obs")
```

```{r echo=FALSE}
panel.cor <- function(x, y, digits = 2, prefix = "", cex.cor, ...) {
    usr <- par("usr")
    on.exit(par(usr))
    par(usr = c(0, 1, 0, 1))
    Cor <- abs(cor(x, y, use = "complete.obs")) # Remove abs function if desired
    txt <- paste0(prefix, format(c(Cor, 0.123456789), digits = digits)[1])
    if(missing(cex.cor)) {
        cex.cor <- 0.4 / strwidth(txt)
    }
    text(0.5, 0.5, txt,
         cex = 1 + cex.cor * Cor) # Resize the text by level of correlation
}


panel.hist <- function(x, ...) {
    usr <- par("usr")
    on.exit(par(usr))
    par(usr = c(usr[1:2], 0, 1.5))
    his <- hist(x, plot = FALSE)
    breaks <- his$breaks
    nB <- length(breaks)
    y <- his$counts
    y <- y/max(y)
    rect(breaks[-nB], 0, breaks[-1], y, col = rgb(0, 1, 1, alpha = 0.5), ...)
    # lines(density(x), col = 2, lwd = 2) # Uncomment to add density lines
}

pairs(pg_adelie[, c(3,4)],
      upper.panel = panel.cor, diag.panel = panel.hist)
```

```{r echo=FALSE}
{ plot(pg_adelie[, c(3,4)], pch = 19)
abline(lm(pg_adelie$bill_depth_mm ~ pg_adelie$bill_length_mm), col = "red", lwd = 3)
text(paste("Correlation:", 
           round(cor(pg_adelie$bill_length_mm, pg_adelie$bill_depth_mm, use = "complete.obs"), 4)),
           x = 44, y = 16, cex = 1.2)
}
```


.EOD.