---
title: "TIL`r format(Sys.Date(), '%Y%m%d')`"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
pg <- palmerpenguins::penguins
library(tidyverse)
library(caret)
```

## dummy variables in R

### ifelse

```{r}
set.seed(123)
pg %>% 
  mutate(dummy_sex = ifelse(sex == "female", 0, 1)) %>% 
  select(sex, dummy_sex) %>%
  sample_n(6, replace = F)
```

```{r}
set.seed(123)
pg %>% 
  mutate(dummy_Chinstrap = ifelse(species == "Chinstrap", 1, 0),
         dummy_Gentoo = ifelse(species == "Gentoo", 1, 0)) %>% 
  select(species, starts_with("dummy_")) %>%
  sample_n(6, replace = F)
```

### model.matrix

```{r}
set.seed(123)
pg %>% 
  model.matrix( ~ species + sex, data = .) %>% .[, -1] %>% 
  bind_cols(na.omit(pg)) %>% 
  sample_n(6, replace = F)
```


### fastDummies::dummy_cols

```{r}
library(fastDummies)
# n category, n dummies
set.seed(123)
pg %>% drop_na() %>% # na omit
  dummy_cols(select_columns = c("species", "sex")) %>% 
  select(starts_with("species"), starts_with("sex")) %>% 
  sample_n(6, replace = F)
```

```{r}
# n category, (n-1) dummies
set.seed(123)
pg %>% drop_na() %>% # na omit
  dummy_cols(select_columns = c("species", "sex"),
             remove_first_dummy = T) %>% 
  select(starts_with("species"), starts_with("sex")) %>% 
  sample_n(6, replace = F)
```


```{r}
# n category, (n-1) dummies, remove original variable
set.seed(123)
pg %>% drop_na() %>% # na omit
  dummy_cols(select_columns = c("species", "sex"), 
             remove_first_dummy = T,
             remove_selected_columns = T) %>% 
  select(starts_with("species"), starts_with("sex")) %>% 
  sample_n(6, replace = F)
```

### caret::dummyVars

```{r}
library(caret)
set.seed(123)
pg %>% 
  dummyVars(~ species + sex, data = ., sep = "_", fullRank = T) %>% 
  predict(newdata = pg) %>% 
  bind_cols(pg) %>% 
  sample_n(6, replace = F)
```

### sjmise::to_dummy

```{r}
library(sjmisc)
pg %>% 
  to_dummy(species, sex, suffix = c("label")) %>% 
  head
```

### modeldb::add_dummy_variables

```{r}
library(modeldb)
pg %>% 
  add_dummy_variables(x = species, values = ("Gentoo"), remove_original = F, auto_values = T) %>% 
  head
```

