---
title: "CV(Coefficient of Variation) in R"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
pg <- palmerpenguins::penguins
library(tidyverse)
library(caret)
```

## CV (Coefficient of Variation)

$$
CV = \frac {\sigma}{\mu}
$$

### Calculating manually

```{r}
udf_cv <- function(x, na.rm = F) {
  sd(x, na.rm = na.rm) / mean(x, na.rm = na.rm)
}
pg_body_cv <- udf_cv(pg$body_mass_g, na.rm = T)
pg_body_cv
```

```{r}
pg %>% 
  mutate(year = as.factor(year)) %>% 
  summarize(across(where(is.numeric), ~ udf_cv(., na.rm = T)))
```

### Calculating with package

```{r}
library(goeveg)
cv(pg$body_mass_g, na.rm = T)
```

```{r}
pg %>% 
  mutate(year = as.factor(year)) %>% 
  summarize(across(where(is.numeric), ~ cv(., na.rm = T))) 
```


### Comparision

```{r}
samp1_1 <- c(1:10); sd(samp1_1)
samp1_2 <- c(1:10)*10; sd(samp1_2)
cv(samp1_1); cv(samp1_2)
```

```{r}
samp2_1 <- rnorm(10, 100, 100); sd(samp2_1)
samp2_2 <- rnorm(10, 1000, 100); sd(samp2_2)
cv(samp2_1); cv(samp2_2)
```


