---
title: "TIL`r format(Sys.Date(), '%Y%m%d')`"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
pg <- palmerpenguins::penguins
library(tidyverse)
library(caret)
```

## read_csv

**They are typically much faster (~10x) than their base equivalents.**  
- https://r4ds.had.co.nz/data-import.html#getting-started 

`data source` https://archive.ics.uci.edu/ml/machine-learning-databases/credit-screening/crx.data   

```
b,30.83,0,u,g,w,v,1.25,t,t,01,f,g,00202,0,+
a,58.67,4.46,u,g,q,h,3.04,t,t,06,f,g,00043,560,+
a,24.50,0.5,u,g,q,h,1.5,t,f,0,f,g,00280,824,+
b,27.83,1.54,u,g,w,v,3.75,t,t,05,t,g,00100,3,+
b,20.17,5.625,u,g,w,v,1.71,t,f,0,f,s,00120,0,+
```

```{r}
url <- "https://archive.ics.uci.edu/ml/machine-learning-databases/credit-screening/crx.data"
data_raw <- read_csv(file = url,
                     col_names = paste0("A", seq(1:16)),
                     na = "?")
head(data_raw)
```

```{r}
data <- data_raw %>% 
  filter(if_any(everything(), ~is.na(.)))
data %>% head
```

```{r}
read_csv("
a,b,c
1,2,3
4,5,6
")
```

```{r}
read_delim("
a;b;c
1;2;3
4;5;6
", delim = ";")
```


```{r}
read_csv("1,2,3\n4,5,6", col_names = c("x", "y", "z"))
```

```{r}
read_csv("a,b\n 1,2,3\n 4,5,6")
read_csv("a,b,c\n 1,2\n 1,2,3,4")
read_csv("a,b\n \"1")
read_csv("a,b\n 1,2\n a,b")
read_csv("a;b\n 1;3")
```








